version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    environment: 
      - HOSTNAME=$HOSTNAME
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    environment:
      - DATABASE_NAME=$MARIADB_DATABASE_NAME
      - DATABASE_USER=$MARIADB_USER
      - DATABASE_PW=$MARIADB_USER_PASSWORD
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_NAME=$MARIADB_DATABASE_NAME
      - WORDPRESS_USER=$MARIADB_USER
      - WORDPRESS_PW=$MARIADB_USER_PASSWORD
    ports:
      - 9000:9000
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data: 

networks:
  inception:
    driver: bridge

