version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    environment: 
      - HOSTNAME=$HOSTNAME
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
  #   volume:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      - DATABASE_NAME=$MARIADB_DATABASE_NAME
      - DATABASE_USER=$MARIADB_USER
      - DATABASE_PW=$MARIADB_USER_PASSWORD
    ports:
      - 3306:3306
    expose:
      - 3306
    # volume:


  # web:
  #   image:
  #   ports:
#       -
#     volume:

# volume:
