version: "3"

services:
  web:
    container_name:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      HOSTNAME: ${HOSTNAME}
    ports:
      - "80"
      - "443"
    volume:
  web:
    image:
    ports:
      -
    volume:
  web:
    image:
    ports:
      -
    volume:

volume:
