version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure
    env_file:
      - .env
    environment: 
      - HOSTNAME=$HOSTNAME
    ports:
      - 443:443
    expose:
      - 443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    env_file:
      - .env
    environment:
      - DATABASE_NAME=$MARIADB_DATABASE_NAME
      - DATABASE_USER=$MARIADB_USER
      - DATABASE_PW=$MARIADB_USER_PASSWORD
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_started
    build: ./requirements/wordpress
    restart: on-failure
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_NAME=$MARIADB_DATABASE_NAME
      - WORDPRESS_USER=$MARIADB_USER
      - WORDPRESS_PW=$MARIADB_USER_PASSWORD
      - WORDPRESS_ADMIN=$WORDPRESS_ADMIN
      - WORDPRESS_ADMIN_PW=$WORDPRESS_ADMIN_PASSWORD
      - WORDPRESS_ADMIN_EMAIL=$WORDPRESS_ADMIN_EMAIL
      - WORDPRESS_GUEST=$WORDPRESS_GUEST
      - WORDPRESS_GUEST_PW=$WORDPRESS_GUEST_PASSWORD
    ports:
      - 9000:9000
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  adminer:
    image: adminer
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: on-failure
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  ftp:
    image: ftp
    container_name: ftp 
    build: 
      context: ./requirements/bonus/ftp
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PW=${FTP_USER_PASSWORD}
    restart: on-failure
    env_file:
      - .env
    ports:
      - 20:20
      - 21:21
    expose:
      - 20
      - 21
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  redis:
    image: redis
    container_name: redis 
    build: ./requirements/bonus/redis
    restart: on-failure
    env_file:
      - .env
    expose:
      - 6379
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  static: 
    image: static
    container_name: static 
    build: ./requirements/bonus/static
    restart: on-failure
    env_file:
      - .env
    expose:
      - 2053
    volumes:
      - static_data:/var/www/html
    networks:
      - inception

  hexo:
    image: hexo
    container_name: hexo
    build: ./requirements/bonus/hexo
    restart: on-failure
    env_file:
      - .env
    expose:
      - 4000
    volumes:
      - hexo_data:/app
    networks:
      - inception


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wordpress
      o: bind
  static_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/static
      o: bind
  hexo_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/hexo
      o: bind

networks:
  inception:
    driver: bridge

